// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Countdown(arg1:string):Promise<void>;

export function RemainingCountdown():Promise<void>;

export function StopCountdown():Promise<void>;
