// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Countdown(arg1) {
  return window['go']['main']['App']['Countdown'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function RemainingCountdown() {
  return window['go']['main']['App']['RemainingCountdown']();
}

export function StopCountdown() {
  return window['go']['main']['App']['StopCountdown']();
}
