// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Countdown(arg1:number):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function RemainingCountdown():Promise<void>;

export function StopCountdown():Promise<void>;
